config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "tasks#index"

  get '/mind_dump', to: "tasks#mind_dump"
  get '/unassigned', to: "tasks#unassigned"

  resources :tasks do
    member do
      patch 'complete'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :description, presence: true

  def complete!
    update_attribute(:time_completed, Time.now)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:edit, :update, :complete, :destroy]

  def index
    @task = Task.new
    uncompleted_tasks = Task.where(time_completed: nil)
    @quad1_tasks = find_tasks_by_quadrant(uncompleted_tasks, 1)
    @quad2_tasks = find_tasks_by_quadrant(uncompleted_tasks, 2)
    @quad3_tasks = find_tasks_by_quadrant(uncompleted_tasks, 3)
    @quad4_tasks = find_tasks_by_quadrant(uncompleted_tasks, 4)
  end

  def mind_dump
    all_tasks = Task.where(time_completed: nil)
    @assigned_tasks = all_tasks.reject {|task| task.quadrant.nil? }
    @unassigned_tasks = find_tasks_by_quadrant(all_tasks, nil)
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_back(fallback_location: root_path)
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:success] = "Task updated"
      redirect_to root_path
    else
      flash.now[:danger] = "Task not updated"
      render :edit
    end
  end

  def complete
    @task.complete!
    flash[:success] = "Task completed"
    redirect_to root_path
  end

  def destroy
    if @task.destroy
      flash[:success] = "Task has been deleted"
      redirect_to root_path
    end
  end

  private
    def find_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:description, :quadrant)
    end

    def find_tasks_by_quadrant(tasks, quadrant)
      tasks.select { |task| task.quadrant == quadrant}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade show") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yatdl</title> <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-toggleable-md fixed-top navbar-inverse bg-info text-white mx-1 mb-3">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="container">
        <a class="navbar-brand" href="/">YATDL</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if params[:action] == "index" %>">
              <a class="nav-link" href="/">To-Do List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link <%= 'active' if params[:action] == "mind_dump" %>" href="mind_dump">Mind Dump</a>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
              </li class="nav-item">
              <li>
                <%= link_to "Sign out", destroy_user_session_path, class: "nav-link", method: :delete %>
              </li>
              <%# <li class="nav-item"> %>
                <%#   <a class="nav-link" href="unassigned">Unassigned Tasks(# of unassigned heregs)</a> %>
                <%# </li> %>
              <!-- <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
              </li> -->
            </ul>
          </div>
      </div>
      </nav>
    <div class="container">
      <%= flash_messages %>
    <%= yield %>
    </div>
    <hr class="my-5">
    <%= params.inspect %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h3>Update Task</h3>
<div class="row">
  <% if @task.errors.any? %>
    <%= pluralize(@task.errors.count, "error") %>
    prohibited this task from being updated.
    <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_for @task do |f| %>
    <%= f.label "Description" %>
    <%= f.text_field :description %>
    <%= f.label "Quadrant" %>
    <%= f.select :quadrant, (1..4) %>
    <%= f.submit "Update Task" %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<!-- Quadrant View -->
<div class="row justify-content-center" id="top-row">
  <div class="col-md-5 quadrant" id="quad1">
    <h4>Urgent</h4>
    <div class="form-group">
      <%= form_for @task do |f| %>
        <%= f.text_field :description, placeholder: "Task Description" %>
        <%= hidden_field :task, :quadrant, value: 1 %>
        <%= f.submit "Create Task", class: "btn btn-primary btn-sm" %>
      <% end %>
    </div>
    <ul class="flex-ul">
      <% @quad1_tasks.each do |task| %>
        <li class="task">
          <div class="flexc">
            <div>
              <%= link_to complete_task_path(task), id: "complete_task_#{task.id}",
                method: :patch do %>
                <span class='checkbox-toggle'>
                  <i class="fa fa-square-o fa-2x icon" aria-hidden="true"></i>
                  <i class="fa fa-check-square-o fa-2x icon" aria-hidden="true"></i>
                </span>
              <% end %>
            </div>
            <div class="flexdescription"><%= task.description %></div>
            <div class="flexoptions">
              <%= link_to edit_task_path(task), id: "edit_task_#{task.id}" do %>
                <div class="icon"><%= fa_icon "pencil", class: "fa-lg" %></div>
              <% end %>
            </div>
            <div>
              <%= link_to task_path(task), id: "delete_task_#{task.id}", method: :delete, data: { confirm: "Are you sure?" }, class: "" do %>
                <div class="icon"><%= fa_icon "trash-o", class: "fa-lg" %></div>
              <% end %>
            </div>
          </div>
        </li>
        <hr>
      <% end %>
    </ul>
  </div>
  <div class="col-md-5 quadrant" id="quad2">
    <h4>Important</h4>
    <div class="form-group">
      <%= form_for @task do |f| %>
        <%= f.text_field :description, placeholder: "Task Description" %>
        <%= hidden_field :task, :quadrant, value: 2 %>
        <%= f.submit "Create Task", class: "btn btn-primary btn-sm" %>
      <% end %>
    </div>
    <ul class="flex-ul">
      <% @quad2_tasks.each do |task| %>
        <li class="task">
          <div class="flexc">
            <div>
              <%= link_to complete_task_path(task), id: "complete_task_#{task.id}",
                method: :patch do %>
                <span class='checkbox-toggle'>
                  <i class="fa fa-square-o fa-2x icon" aria-hidden="true"></i>
                  <i class="fa fa-check-square-o fa-2x icon" aria-hidden="true"></i>
                </span>
              <% end %>
            </div>
            <div class="flexdescription"><%= task.description %></div>
            <div class="flexoptions">
              <%= link_to edit_task_path(task), id: "edit_task_#{task.id}" do %>
                <div class="icon"><%= fa_icon "pencil", class: "fa-lg" %></div>
              <% end %>
            </div>
            <div>
              <%= link_to task_path(task), id: "delete_task_#{task.id}", method: :delete, data: { confirm: "Are you sure?" }, class: "" do %>
                <div class="icon"><%= fa_icon "trash-o", class: "fa-lg" %></div>
              <% end %>
            </div>
          </div>
        </li>
        <hr>
      <% end %>
    </ul>
  </div>
</div>
<div class="row justify-content-center">
  <div class="col-md-5 quadrant" id="quad3">
    <h4>Delegate</h4>
    <div class="form-group">
      <%= form_for @task do |f| %>
        <%= f.text_field :description, placeholder: "Task Description" %>
        <%= hidden_field :task, :quadrant, value: 3 %>
        <%= f.submit "Create Task", class: "btn btn-primary btn-sm" %>
      <% end %>
    </div>
    <ul class="flex-ul">
      <% @quad3_tasks.each do |task| %>
        <li class="task">
          <div class="flexc">
            <div>
              <%= link_to complete_task_path(task), id: "complete_task_#{task.id}",
                method: :patch do %>
                <span class='checkbox-toggle'>
                  <i class="fa fa-square-o fa-2x icon" aria-hidden="true"></i>
                  <i class="fa fa-check-square-o fa-2x icon" aria-hidden="true"></i>
                </span>
              <% end %>
            </div>
            <div class="flexdescription"><%= task.description %></div>
            <div class="flexoptions">
              <%= link_to edit_task_path(task), id: "edit_task_#{task.id}" do %>
                <div class="icon"><%= fa_icon "pencil", class: "fa-lg" %></div>
              <% end %>
            </div>
            <div>
              <%= link_to task_path(task), id: "delete_task_#{task.id}", method: :delete, data: { confirm: "Are you sure?" }, class: "" do %>
                <div class="icon"><%= fa_icon "trash-o", class: "fa-lg" %></div>
              <% end %>
            </div>
          </div>
        </li>
        <hr>
      <% end %>
    </ul>
  </div>
  <div class="col-md-5 quadrant" id="quad4">
    <h4>Time Wasters</h4>
    <div class="form-group">
      <%= form_for @task do |f| %>
        <%= f.text_field :description, placeholder: "Task Description" %>
        <%= hidden_field :task, :quadrant, value: 4 %>
        <%= f.submit "Create Task", class: "btn btn-primary btn-sm" %>
      <% end %>
    </div>
    <ul class="flex-ul">
      <% @quad4_tasks.each do |task| %>
        <li class="task">
          <div class="flexc">
            <div>
              <%= link_to complete_task_path(task), id: "complete_task_#{task.id}",
                method: :patch do %>
                <span class='checkbox-toggle'>
                  <i class="fa fa-square-o fa-2x icon" aria-hidden="true"></i>
                  <i class="fa fa-check-square-o fa-2x icon" aria-hidden="true"></i>
                </span>
              <% end %>
            </div>
            <div class="flexdescription"><%= task.description %></div>
            <div class="flexoptions">
              <%= link_to edit_task_path(task), id: "edit_task_#{task.id}" do %>
                <div class="icon"><%= fa_icon "pencil", class: "fa-lg" %></div>
              <% end %>
            </div>
            <div>
              <%= link_to task_path(task), id: "delete_task_#{task.id}", method: :delete, data: { confirm: "Are you sure?" }, class: "" do %>
                <div class="icon"><%= fa_icon "trash-o", class: "fa-lg" %></div>
              <% end %>
            </div>
          </div>
        </li>
        <hr>
      <% end %>
    </ul>
  </div>

</div>
<!-- /Quadrant View -->


  <!-- <h3>Tasks</h3>
  <ul>
    <% @quad1_tasks.each do |task| %>
      <li>
        <%= task.description %>(Q<%= task.quadrant %>)
        <%= link_to "Complete", complete_task_path(task), id: "complete_task_#{task.id}",
            method: :patch, data: { confirm: "Are you sure?" } %>
        <%= link_to "Edit", edit_task_path(task), id: "edit_task_#{task.id}" %>
        <%= link_to "Delete", task_path(task), id: "delete_task_#{task.id}",
            method: :delete, data: { confirm: "Are you sure?" },
            class: "" %>
      </li>
    <% end %>
  </ul> -->

app/views/tasks/mind_dump.html.erb
<h1 class="text-center">This is Mind Dump Page.</h1><br>
<h3 class="text-center">List everything you have to do here.</h3>

<div class="mind-dump">
  <div class="form-group">
      <%= form_for @task do |f| %>
        <%= f.text_field :description, placeholder: "Task Description", autofocus: true %>
        <%= f.select :quadrant, [["Unassigned",nil],["Urgent",1],["Important",2],["Delegate",3],["Time Wasters",4]], selected: nil %>
        <%= f.submit "Create Task", class: "btn btn-primary btn-sm" %>
      <% end %>
    </div>

  <ul>
    <% @unassigned_tasks.each do |task| %>
      <li><%= "#{task.description} (unassigned)" %></li>
      <hr>
    <% end %>
    <% @assigned_tasks.each do |task| %>
      <li><%= "#{task.description} (#{task.quadrant})" %></li>
      <hr>
    <% end %>
  </ul>
</div>